// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: MediaTrackerUI

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Screen1, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Screen1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabView1 = lv_tabview_create(ui_Screen1, LV_DIR_TOP, 50);
    lv_obj_set_width(ui_TabView1, 325);
    lv_obj_set_height(ui_TabView1, 38);
    lv_obj_set_x(ui_TabView1, -1);
    lv_obj_set_y(ui_TabView1, -102);
    lv_obj_set_align(ui_TabView1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_TabView1, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_TabView1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_TabView1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    
    lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_TabView1), lv_color_hex(0xffffff),
                              LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_TabView1), 255,  LV_PART_ITEMS | LV_STATE_CHECKED);

    ui_TabPage1 = lv_tabview_add_tab(ui_TabView1, "MUSIC");
    lv_obj_clear_flag(ui_TabPage1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabPage2 = lv_tabview_add_tab(ui_TabView1, "DISCORD");

    ui_TabPage3 = lv_tabview_add_tab(ui_TabView1, "TASK-MGR");

    ui_TabPage4 = lv_tabview_add_tab(ui_TabView1, "SETTINGS");

    uic_Screen1 = ui_Screen1;
    uic_TabView1 = ui_TabView1;

}
