// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: MediaTrackerUI

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabView1 = lv_tabview_create(ui_Screen1, LV_DIR_TOP, 50);
    lv_obj_set_width(ui_TabView1, 325);
    lv_obj_set_height(ui_TabView1, 38);
    lv_obj_set_x(ui_TabView1, -2);
    lv_obj_set_y(ui_TabView1, -101);
    lv_obj_set_align(ui_TabView1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_TabView1, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_TabView1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_TabView1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabPage1 = lv_tabview_add_tab(ui_TabView1, "MUSIC");
    lv_obj_clear_flag(ui_TabPage1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabPage2 = lv_tabview_add_tab(ui_TabView1, "DISCORD");

    ui_TabPage3 = lv_tabview_add_tab(ui_TabView1, "TASK-MGR");

    ui_TabPage4 = lv_tabview_add_tab(ui_TabView1, "SETTINGS");

    ui_Spinner1 = lv_spinner_create(ui_Screen1, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 80);
    lv_obj_set_height(ui_Spinner1, 80);
    lv_obj_set_x(ui_Spinner1, 4);
    lv_obj_set_y(ui_Spinner1, 16);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    uic_Screen1 = ui_Screen1;
    uic_TabView1 = ui_TabView1;

}
